Initial commit for canonical validator
TaskarCenterAtUW/TDEI-mobilitydata-canonical-validator pull request #1
Opened 2024-02-12 07:31 UTC by sujata-m

This PR contains - 

- Added code for canonical validator
- Added unit test cases
- Added Changelog
- Updated readme
- Add CI/CD Pipelines

### Test Cases
```shell

>  python -m unittest discover -v tests/unit_tests
test_validate_failed_upload (test_canonical_validator.TestCanonicalValidator) ... ok
test_validate_successful_upload (test_canonical_validator.TestCanonicalValidator) ... ok
test_validate_failure_dataset_upload (test_canonical_validator.TestCanonicalValidatorFailureWithDatasets) ... ok
test_validate_successful_upload (test_canonical_validator.TestCanonicalValidatorSuccessWithDatasets) ... ok
test_get_result_url (test_constants.TestConstants) ... ok
test_get_info_failure (test_gtfs_validator.TestGTFSValidatorData) ... ok
test_get_info_success (test_gtfs_validator.TestGTFSValidatorData) ... ok
test_get_mobility_data_failure (test_gtfs_validator.TestGTFSValidatorData) ... ok
test_get_mobility_data_success (test_gtfs_validator.TestGTFSValidatorData) ... ok
test_upload_failure (test_gtfs_validator.TestGTFSValidatorData) ... ok
test_upload_success (test_gtfs_validator.TestGTFSValidatorData) ... ok

----------------------------------------------------------------------
Ran 11 tests in 86.930s

OK
```

### Coverage Report

```shell

>  coverage report
Name                                              Stmts   Miss  Cover
---------------------------------------------------------------------
src/example.py                                       13     13     0%
src/gtfs_canonical_validator/__init__.py             31      0   100%
src/gtfs_canonical_validator/constants.py             7      0   100%
src/gtfs_canonical_validator/gtfs_validator.py       44      0   100%
src/gtfs_canonical_validator/models/response.py       4      0   100%
src/gtfs_canonical_validator/version.py               1      0   100%
---------------------------------------------------------------------
TOTAL                                               100     13    87%

```

2024-02-19 18:10 UTC, sureshgaussian requested changes
Please change the code as requested.

2024-02-19 18:10 UTC, sureshgaussian commented on src/example.py
> +    canonical_validator = CanonicalValidator(zip_file='./src/assets/valid.zip')
valid.zip is not in the assets folder.

2024-02-19 18:10 UTC, sureshgaussian commented on src/mobility_canonical_validator/mobility_data.py
> +class MobilityData:
Change this to GTFSValidator

2024-02-19 18:10 UTC, sureshgaussian commented on README.md
> +- or `pip install mobility_canonical_validator`
change the name of the package to gtfs_canonical_validator

2024-02-19 18:10 UTC, sureshgaussian commented on src/mobility_canonical_validator/mobility_data.py
> +                return self.get_mobility_data(url=url, count=count + 1)
this uses recursion. better to move this to a loop to avoid memory issues.

2024-02-19 18:10 UTC, sureshgaussian commented on src/mobility_canonical_validator/mobility_data.py
> +                self.logger.info('skipping tried 5 times already')
change 5 to max_retries.

2024-02-19 18:10 UTC, sureshgaussian commented on src/mobility_canonical_validator/mobility_data.py
> +        self.timeout = 5
why don't we move these two constants also into 'constants.py'?

2024-02-19 18:10 UTC, sureshgaussian commented on src/mobility_canonical_validator/mobility_data.py
> +        self.max_retries = 10
@TaskarCenterAtUW/tdei-gs , is 50 secs enough to handle the biggest file we will encounter? Could we check with David or someone from MobilityData on what they suggest as the max time out for the validator?

2024-02-28 16:54 UTC, sureshgaussian approved these changes
Ran the code on my machine. Looked through the code. There are minor changes we could make, but we can pick them up later.
"ERROR:CANONICAL_VALIDATOR:Error: 404 Client Error: Not Found for url: https://gtfs-validator-results.mobilitydata.org/53744af7-1bce-40c6-827e-55e6f9358e79/report.json
INFO:CANONICAL_VALIDATOR:Retrying Request Count To Get Validation Result: 1
INFO:CANONICAL_VALIDATOR:Got Success Response From Mobility"
in the logs confuses someone. These are from the response from the requests call I believe. We need to find a way to suppress showing Error while the processing is still going on.

2024-02-28 17:46 UTC, susrisha approved these changes

2024-02-28 21:16 UTC, merged